//*******************************************************************
// SIMULATION PARAMETER FILE
//*******************************************************************
#include "TestStat/Para.CPP"
//"Test/Para.CPP"
//"../Trajec/Para.CPP"
//#include "../Test/Para.CPP"
//#include "../TestTaurus/Para.CPP"

//#include "../TugK013f2N20/Para.CPP"
//#include "../TugK013f1N20/Para.CPP"
//#include "../TugK013f05N20/Para.CPP"
//#include "../TugK013f01N20/Para.CPP"
//#include "../TugK013f05N20KIni15/Para.CPP"
//#include "../TugK013f05N20KIni19/Para.CPP"
//#include "../TugK013f05N20KIniP19KIniM0/Para.CPP"
//#include "../TugK013f05N20KIniP20KIniM0/Para.CPP"
//#include "../TugK013f1N100KIni1/Para.CPP"
//#include "../TugK013f1N100KIniP90KIniM0/Para.CPP"
//#include "../TugK013f1N50KIniP40KIniM0/Para.CPP"
//#include "../TugK013f1N50KIni1/Para.CPP"
//#include "../TugK013f1N20KIniP20KIniM0/Para.CPP"
//#include "../TugK013f1N20KIni1/Para.CPP"
//#include "../TugK013f1N10KIniP10KIniM0/Para.CPP"
//#include "../TugK013f1N10KIni1/Para.CPP"
//#include "../TugK013f1N5KIniP5KIniM0/Para.CPP"
//#include "../TugK013f1N5KIni1/Para.CPP"

//#include "../TugK013f10N10/Para.CPP"



//*******************************************************************
// PARAMETERS
//*******************************************************************

const double equilibrationTime = 50;

